minVersion: "0.15.0"
github:
  owner: getsentry
  repo: snuba-sdk
changelog: CHANGES.md
changelogPolicy: auto
artifactProvider:
  name: github
targets:
  - name: github
  - name: pypi

requireNames:
  - /^snuba_sdk-.+-py2.py3-none-any.whl$/
