name: tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Run linters
        run: |
          tox -e linters

  tests:
    name: Run tests

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.4,3.5,3.6,3.7,3.8,3.9]

    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: Run tests
        run: |
          tox
