name: tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv
      - name: Run linters
        run: |
          make lint

  tests:
    name: Run tests

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python: [3.7,3.8,3.9,"3.10",3.11]

    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r test-requirements.txt
    - name: Run tests
      run: |
        pytest
